### ISSUE TITLE
V2 TODO

### ISSUE THREAD

**Issue by ericholscher** [rtfd/readthedocs-build#8]
I basically re-wrote the complete rtd-build cli.
Here is a current backlog of open tasks:

- [X] reading readthedocs.yml configs
- [X] rtd-build cli
- [X] ~~running build inside a virtualenv~~
- [x] building html docs using sphinx
- [X] sphinx json output for search (will be placed in the `search_data` directory)
- [X] ~~support for virtualenv's `--system-site-packages`~~
- [ ] ~~support for requirements.txt~~
- [X] support for `python setup.py install`
- [ ] defaulting to `sphinx_rtd_theme`
- [ ] sphinx dirhtml support
- [ ] sphinx singlehtml support (and local media build)
- [ ] sphinx pdf support
- [ ] sphinx epub support
- [ ] auto-create index.html file if none exists
- [ ] ~~mkdocs support~~
- [ ] awesome logging
- [ ] remove `.doctree` files from output

All implemented things are tested very well. Tests can be run with `tox`. Instructions in the README have been updated.

To run a quick sample of the builder, do:

```bash
cd integration_tests/minimal_project/
rtd-build
```

This will output the rendered docs in `_readthedocs_build/docs/html/`.

Currently we support the following config options in `readthedocs.yml`:

```yaml
name: docs  # required, arbitrary
type: sphinx  # required, only sphinx is supported at the moment
base: docs-en/  # the base directory of the source files
```

Continued from #6
